#ifndef __LIB2D__
#define __LIB2D__

#include "control.h"
#include "display.h"
#include "color.h"
#include "mono.h"
#include "button.h"
#include "check_button.h"
#include "label_button.h"
#include "pictures_button.h"
#include "textbox.h"
#include "toggle_button.h"
#include "textbox_alpha.h"
#include "textbox_num.h"
#include "multi.h"
#include "box.h"
#include "hbox.h"
#include "vbox.h"
#include "container.h"
#include "context.h"
#include "popup.h"
#include "info_popup.h"
#include "table.h"
#include "object.h"
#include "animation.h"
#include "darea.h"
#include "image.h"
#include "label.h"
#include "label_link.h"
#include "font.h"
#include "items_classes.h"
#include "rect.h"
#include "surface.h"
#include "timer.h"
#include "engine.h"
#include "event.h"
#include "events_classes.h"
#include "key_code.h"
#include "keyboard_down.h"
#include "keyboard_up.h"
#include "keyboard_event.h"
#include "mouse_down.h"
#include "mouse_motion.h"
#include "mouse_up.h"
#include "mouse_event.h"
#include "system_active.h"
#include "system_context_switch.h"
#include "system_quit.h"
#include "system_resize.h"
#include "system_event.h"
#include "graphics.h"
#include "signal_lister.h"
#include "signal_maker.h"
#include "c_gui_maker.h"
#include "window.h"
#include "sound_manager.h"


#include "c_buffer.h"
#include "c_buffer_requirements.h"
#include "c_file_reader.h"
#include "c_file_reader_requirements.h"
#include "c_threader.h"
#include "fc_timer.h"
#include "libid.h"
#include "ns_macros.h"

#include "ns_math.h"

#include "ns_var.h"



#endif
